name: CI

on:

  push:

    branches:

      - main

  pull_request:

    branches:

      - main


jobs:

  build:

    runs-on: ubuntu-latest


    strategy:

      matrix:

        node-version: [22]


    steps:

      - name: Checkout repository

        uses: actions/checkout@v4


      - name: Setup Node.js

        uses: actions/setup-node@v4

        with:

          node-version: ${{ matrix.node-version }}


      # Server

      - name: Install server dependencies

        run: |

          cd server

          npm install


      - name: Build server

        run: |

          cd server

          npm run build --if-present


      # Client

      - name: Install client dependencies

        run: |

          cd client

          npm install


      - name: Build client

        run: |

          cd client

          npm run build